### ISSUE TITLE
simple feature

### ISSUE THREAD

**Issue by dakni** [ISAAKiel/c14bazAAR#1]
These lines show how to build a simple feature object from the downloaded data. It could directly be implemented in order to have the downloaded data directly as sf object.

```r
library(sf)
a <- c14databases::get_CALPAL()
a_sf <- st_sfc(st_multipoint(as.matrix(a[,c('lon','lat')])), crs = st_crs(4326)) %>%
  st_cast("POINT") %>%
  st_sf(data = a, geom = .)

plot(rain_sf["data.c14age"])
```

i'll test a bit.

**Comment by nevrome** [comment]
The last line of your code example seems to be wrong?

I would love to have an `as_sf.c14_date_list()` function. A c14_date_list is a modified tibble ("c14_date_list", "tbl_df","tbl", "data.frame"). Therefore the transformation seems to be just as simple to implement as you describe it. Do you want to prepare a pull request?

For a dedicated plot function I would like to avoid sf. It's a big dependency that should remain optional (Suggests) and a good plot function for a c14 database goes way beyond the aspect of spatial distribution. Actually it's so highly dependent on the research question, that I'm not sure whether a plot function is even useful in the context of this package. 

Another thing: In the `estimate_spatial_quality()` function I'm using sp to check the coordinate defined country attribution of the dates and compare it with the predefined country value in the database. This seems arbitrary, but surprisingly it allows a good first estimate of the coordinate information quality. Would you mind taking a quick look at the code and tell me, whether this could be easily implemented with sf instead of sp?

**Comment by dakni** [comment]
Salut.

Your implementation of `estimate_spatial_quality` is fine, in my opinion.

As far as I know now the functions in the `sf` realm for your tasks would be `sf::st_set_crs(4326)` to set the CRS to WGS84 as this is the CRS of the rworldmap

`sf::st_intersects` can be seen as loose substitute for `over` for your country-location test. As soon as I stumble upon a simpler solution I'll let you know.

about my code above and to myself: RTFM. *hoops* Nevermind. Here is the correct one (Download 14C data with your package, create sf object, set crs.):

```
a <- c14databases::get_CALPAL()
a_sf <- a %>%  
  sf::st_as_sf(coords = c('lon','lat')) %>%
  sf::st_set_crs(4326)
plot(a_sf["c14age"])
```
 
However, your class is dropped during this process:

```
> class(a_sf)
[1] "sf"         "tbl_df"     "tbl"        "data.frame"
```

Hence, it would only make sense to use it with a spatial plot function that integrates mapview (at least if you want that your class is still around).

**Comment by nevrome** [comment]
Thanks for the review, Daniel! 

Concerning the plot function I'm still not sure what's the best way to handle this. Maybe a plot function with two perspectives: A spatial and temporal view. It's a great idea to use mapview for the spatial one. The temporal view could be something like the one in the upper right corner in the neolithicrc app.

**Comment by nevrome** [comment]
See #10 and #13
