### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/c14bazAAR#28]
I thought about putting c14bazAAR and also neolithicRC into the [public domain](http://unlicense.org/). What do you think @dirkseidensticker, @dakni?

**Comment by dirkseidensticker** [comment]
seems okay for me 👍

**Comment by dakni** [comment]
legal issues...*grrrr*

I would prefer a copyleft license to make sure that nobody can "close"/hide the sources in the future. Of course c14bazAAR is just a small tool but it should be a general principle. 

So my vote goes to GNU GPL v3

btw.: do you know this mooc on the topic: http://digitalfree.info/FreeDigitalSociety/index.html [it has an "epic" soundtrack as well ;) ]

**Comment by dirkseidensticker** [comment]
I'm always preferring permissive licenses like MIT over GPLv3. I've seen the share-alike of GPL's always as interfering with my personal choice of licence, but can see the sense of fairness in it.  And somehow I always sided more with https://www.youtube.com/watch?v=PaKIZ7gJlRU 😉

**Comment by dakni** [comment]
thanks for the link! I understand his point and it is interesting to think about (perhaps its again my disbelief in the honesty of people why I focus on licenses enforcing freedom). Nevermind, I am still struggling to get my head around these license issues. In the end **you two should decide**, since the whole idea of the package and all the hard crafting and thinking work was done by you. :)

**Comment by nevrome** [comment]
Thanks for your very valuable input. I think I grasp the major issues now. 

I'm intrigued by the nonchalance of the Unlicense and the [WTFPL](https://en.wikipedia.org/wiki/WTFPL). I'm also pretty sure that nobody can do serious harm with this code even in a proprietary tool. So I would prefer to remove really all constraints to share, modify and reuse it. There's a very small risk that somebody copies and distributes the code without any or minor changes and gets all the sweet fame for it. But archaeology is a small subject with strong shaming of scientific misconduct. So I don't expect this to happen and I accept the risk. 

Beyond that I don't think that this only our decision. You too, Daniel, contributed code by now and every contributor should know the terms and conditions up front. I will ask the other ISAAK members tomorrow about their opinion. 

Maybe @kacebe and @benmarwick have a minute to leave a short comment about their opinion. I know that you are also well-versed in this topic.

**Comment by benmarwick** [comment]
I usually prefer MIT for myself, mostly because I see it widely used in the R community, and, if I understand correctly, any commercial archaeologist could use my code without concern. However, I think awareness of licensing is so low in the archaeological community they would probably use it regardless of the licence! Anyway, for this particular case, I don't have a strong recommendation about MIT versus GPL, you should choose whatever the main contributors agree on. But I would discourage using exotic minor licenses because they might confuse potential users who are more accustomed to the common ones, and drive them away from using your work

**Comment by nevrome** [comment]
Thanks for your comment Ben. Makes sense.

We will discuss this in the ISAAK meeting tomorrow to make a final decision.

**Comment by nevrome** [comment]
Oh - I forgot to document the result of our discussion. GPL2 it is. We embrace copyleft: A political statement.
