### ISSUE TITLE
spatial quality estimation

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/c14bazAAR#4]
[c14bazAAR/R/c14_date_list_estimate_spatial_quality.R](https://github.com/ISAAKiel/c14bazAAR/blob/master/R/c14_date_list_estimate_spatial_quality.R)

- Can it be done better? Right now the spatial quality estimation is limited to some general observations and the comparison of the coordinates and the country information. Can we do more? Maybe a cross validation of site locations?
- Can it be done faster?

**Comment by dirkseidensticker** [comment]
Maybe one might consider to reference site names with http://www.geonames.org/ (see http://www.geonames.org/export/web-services.html for API).

**Comment by nevrome** [comment]
Sounds promising! Some of the steps should be coordinated with the thesaurification group, to avoid contradictory solutions to the same problems. @preiaen & @ctietze91

**Comment by nevrome** [comment]
Ok - I tried now to understand your plans. Some questions and comments:

- What are these scenarios? What does *control possible* mean?

> • supply country dataset (either using a package or as localized
dataset)

- I suggest to use `rworldxtra`. Works, is already available in R and we don't have to care about updates. 

> • fuzzyjoin based comparison of mentioned countrynames with supplied
dataset (sringdist_join)

- countrynames before or after the thesaurification? 

> • throw a warning when countryname and coordinate do not match (case specific)

- No warnings please. They are difficult to handle. What should a user do with 10.000 warnings?

> • return two datasets:
> 1. only the correct/trustworthy data
> 2. all data with corrected and commentary column

- Please only one dataset with additional columns. The workflow is a lot less smooth if you have to subset a list somewhere in between. But maybe I misunderstand this.

> • retrieve sitenames from coordinates (using geonames); though this cannot be checked

A very interesting idea! That could be an extra function. Does geonames have an API request limit?

**Comment by kschmuetz** [comment]
Hi,
I checked and unfortunately the geonames package needs a username (so registration would be necessary...) and has a limit of 2000 querys/hour and a maximum of 30 000 querys/day (http://www.geonames.org/export/).
So maybe we have to think of something else...

**Comment by dakni** [comment]
Salut!

- "control possible" means that is it possible to check country definition with coordinates and to see whether the fit or not.

- `rwoldxtra` has to be installed as well. Personally, I do have no preference to use this over another package offering these information because most of them are based on NaturalEarthData. Perhaps it is worthwhile to think about a dataset that implements country information in a `sf` way. We'll investigate that. 

- thesaurification...I think I do not yet get the point of this thing, perhaps because it is also parser-related and by now we work on a, already assembled c14_date_thing. In case `fuzzyjoin` is used it depends on the level of reliability: `stringdist_join` based only on countrynames can be done at a very early stage. `stringdist_join` based on countrynames retrieved from coordinates is possible only after spatializing the dataset.

- warnings: agreed

- one instead of two datasets: ok.

- geonames API like the one of google is restricted (afaik). I think ~2000 !? Perhaps we can go with osm. In this case all other meta-information (country etc.) could be taken from osm. One advantage is, that osm is hosted on different servers and when a request limit is reached one could switch servers.

**Comment by nevrome** [comment]
This issue became obsolete with the discussion in #6
