### ISSUE TITLE
version 1.0

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/c14bazAAR#41]
Thanks for the great work so far @dirkseidensticker, @dakni, @MartinHinz, @yesdavid, @whamer, @kschmuetz and all the other people from ISAAK

I once more invested some time over the weekend to polish c14bazAAR. There still are some rough edges, but we're getting closer. I would like to ask you to invest some time this week to bring this to an happy end in a final feat of strength. 

Now that there's a somehow useful README, everybody should be able to see the big picture. Please go through the documentation, test some functions and criticize/improve/streamline whatever comes to your attention. Think of this as a first compilation of the complete draft of a paper we wrote together.

**Comment by dakni** [comment]
ui...thanks @nevrome ! :+1: I like the documentation and I am impressed by the advanced code and professionality that permeates the package. I think this is a large step forward for ISAAK and the contributing members and at least I learned and learn a lot during the process.

**Comment by MartinHinz** [comment]
I absolutely agree, that is a fine piece of work, mainly (if not nearly exclusive) done by Clemens, and I am very happy to be part of this project

Countdown for Release 10...9...8...7...

**Comment by nevrome** [comment]
The release has to wait until the next CRAN release of readr (https://github.com/tidyverse/readr/issues/750 & https://github.com/tidyverse/readr/issues/833)

**Comment by stianlagstad** [comment]
Sorry for barging in and asking what might be a stupid question, but: Is there any way to see or check approximately when the next release of readr will be? Will that be at the same time as a new CRAN release? I'm not sure how all of that works, and my efforts of googling things related to "next cran version" / "readr next version" / "how often is cran released" didn't pan out. I ask because I'm waiting for the same readr change to be released.

Thank you!
